SELECT *
FROM HOSPITAL.TRANSACTIONS Y JOIN HOSPITAL.patient Z
ON Y.pait_id = Z.pait_id

SELECT Z.name+ ' PAID THE SUM OF ' + Y.TRAN_ID +'ONLY'
FROM HOSPITAL.TRANSACTIONS Y JOIN HOSPITAL.patient Z
ON Y.pait_id = Z.pait_id